[[tls.certificates]] #first certificate
  certFile = "/certs/aeris.lan.crt"
  keyFile = "/certs/aeris.lan.key"
[tls.stores]
  [tls.stores.default]
   [tls.stores.default.defaultCertificate] 
      certFile = "/certs/aeris.lan.crt"
      keyFile = "/certs/aeris.lan.key"