version: "2.1"
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=$TIMEZONE
    volumes:
      - $DOCKER_CONFIGS_PATH/adguard/work:/opt/adguardhome/work
      - $DOCKER_CONFIGS_PATH/adguard/conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/udp
    restart: unless-stopped

    labels:
      traefik.enable: true
      traefik.http.routers.adguard.rule: Host(`adguard.localhost`) || Host(`adguard.${TRAEFIK_HOST-lan}`)
      traefik.http.routers.adguard.entrypoints: ${TRAEFIK_ENTRYPOINTS-web,websecure}
      traefik.http.routers.adguard.tls: ${SSL_ENABLE-false}
      traefik.http.services.adguard.loadbalancer.server.port: 3000
      traefik.docker.network: traefik_net
    networks:
      traefik_net:
      default:

networks:
  default:
  traefik_net:
    external: true
