version: '3'
services:
  jupyter-datasci:
    image: jupyter/datascience-notebook
    command:
      - start-notebook.sh
    volumes:
      - ~/DataComposer/notebooks:/home/jovyan/work/notebooks/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.datasci.rule: Host(`datasci.localhost`) || Host(`datasci.${TRAEFIK_HOST-lan}`)
      traefik.http.routers.datasci.entrypoints: ${TRAEFIK_ENTRYPOINTS-web,websecure}
      traefik.http.routers.datasci.tls: ${SSL_ENABLE-false}
      traefik.http.services.datasci.loadbalancer.server.port: 8888
      traefik.http.routers.metabase.middlewares: traefik@docker
    environment:
      JUPYTER_ENABLE_LAB: ${JUPYTER_ENABLE_LAB-yes}
      NB_UID: $UID
      NB_GID: $GID
    networks:
      - traefik_net
networks:
    traefik_net:
      external: true
