version: '2.4'

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    labels:
      - traefik.enable=false
    networks:
      mysql:
    environment:
      MYSQL_ROOT_PASSWORD: ${DBS_PASSWORD-examplepassword}    
  redis:
    image: redis:5-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    labels:
      - traefik.enable=false
    networks:
        mysql:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    restart: unless-stopped
    mem_limit: 768m
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic:/usr/share/elasticsearch/data 
    labels:
      - traefik.enable=true
      - traefik.http.routers.elastic.rule=Host(`elastic.localhost`)
      - traefik.http.routers.elastic.entrypoints=web,websecure
      - traefik.http.services.elastic.loadbalancer.server.port=9200
    networks:
        traefik_net:
networks:
    mysql:
    traefik_net:
      external: true
volumes:
  mariadb:
  elastic: