version: '2.3'

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    labels:
      - traefik.enable=false
    networks:
      mysql:
    environment:
      MYSQL_ROOT_PASSWORD: ${DBS_PASSWORD-examplepassword}    
  redis:
      image: redis:5-alpine
      restart: unless-stopped
      ports:
        - "6379:6379"
      labels:
        - traefik.enable=false
      networks:
          mysql:
networks:
    mysql:
volumes:
  mariadb: