version: '3.3'

services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.defaultRule=Host(`{{ trimPrefix `/` .Name }}.localhost`)
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.file.directory=/etc/traefik/
      - --providers.file.watch=true
      - --log.level=INFO
      - --serversTransport.insecureSkipVerify=true
    restart: always
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/.passwd:/.passwd
      - ${PWD}/certs/:/certs
      - ${PWD}/configs/traefik/:/etc/traefik/
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`monitor.localhost`) || Host(`monitor.${TRAEFIK_HOST-lan}`) 
      # traefik.http.routers.traefik.middlewares: traefik@docker
      traefik.http.routers.traefik.entrypoints: ${TRAEFIK_ENTRYPOINTS-web,websecure}
      traefik.http.routers.traefik.tls: ${SSL_ENABLE-false}
      traefik.http.routers.redirs.rule: hostregexp(`{host:.+${TRAEFIK_HOST-lan}}`)
      traefik.http.routers.redirs.entrypoints: web
      traefik.http.routers.redirs.middlewares: redirect-to-https
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.http.middlewares.traefik.basicauth.usersfile: /.passwd
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
    networks:
        net:
  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    labels:
      traefik.http.routers.portainer.rule: Host(`portainer.ssl.localhost`) || Host(`portainer.localhost`) || Host(`portainer.${TRAEFIK_HOST-lan}`) 
      traefik.enable: true
      traefik.http.routers.portainer.entrypoints: ${TRAEFIK_ENTRYPOINTS-web,websecure}
      traefik.http.routers.portainer.tls: ${SSL_ENABLE-false}
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    networks:
        net:
  watchtower:
    image: containrrr/watchtower:latest
    labels:
      traefik.enable: false
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
    net:
volumes:
  portainer: