version: '3.3'

services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.defaultRule=Host(`{{ trimPrefix `/` .Name }}.localhost`)
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    restart: always
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/.passwd:/.passwd
    labels:
      traefik.http.routers.traefik.rule: Host(`monitor.localhost`) || Host(`monitor.${TRAEFIK_HOST-lan}`) 
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.enable: true
      traefik.http.routers.traefik.entrypoints: web,websecure
      traefik.http.middlewares.traefik.basicauth.usersfile: /.passwd
      traefik.http.routers.metabase.middlewares: traefik@docker
    networks:
        net:
  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    labels:
      traefik.http.routers.portainer.rule: Host(`portainer.localhost`) || Host(`portainer.${TRAEFIK_HOST-lan}`) 
      traefik.enable: true
      traefik.http.routers.portainer.entrypoints: web,websecure
    networks:
        net:
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
    net:
volumes:
  portainer: