version: '2.4'

services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
        restart: unless-stopped
        mem_limit: 768m
        environment:
          discovery.type: "single-node"
          xpack.security.enabled: "false"
        # ports:
        #   - "9200:9200"
        volumes:
          - elastic:/usr/share/elasticsearch/data 
        labels:
          - traefik.enable=true
          - traefik.http.routers.elastic.rule=Host(`elastic.localhost`)
          - traefik.http.routers.elastic.entrypoints=web,websecure
          - traefik.http.services.elastic.loadbalancer.server.port=9200
        networks:
            traefik_net:
networks:
    elastic:
    traefik_net:
        external: true
volumes:
    elastic: