version: '3'
services:
  jupyter-spark:
    image: jupyter/all-spark-notebook
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks/
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jupyter.rule=Host(`jupyter.localhost`)
      - traefik.http.routers.jupyter.entrypoints=web,websecure
      - traefik.http.services.jupyter.loadbalancer.server.port=8888
      - traefik.http.routers.spark0.rule=Host(`spark.localhost`)
      - traefik.http.routers.spark0.entrypoints=web,websecure
      - traefik.http.services.spark0.loadbalancer.server.port=4040
      - traefik.http.routers.spark1.rule=Host(`1.spark.localhost`)
      - traefik.http.routers.spark1.entrypoints=web,websecure
      - traefik.http.services.spark1.loadbalancer.server.port=4041
    environment:
      JUPYTER_ENABLE_LAB: ${JUPYTER_ENABLE_LAB-yes}
    networks:
      - traefik_net
networks:
    traefik_net:
      external: true
