version: '3'
services:
  jupyter-spark:
    image: jupyter/all-spark-notebook
    command:
      - start-notebook.sh
      - --LabApp.token='$JUPYTER_PASSWORD'
      - --NotebookApp.token='$JUPYTER_PASSWORD'
      # - --LabApp.password='${JUPYTER_PASSWORD-sha1:975a9425135d:7d3618cc7517de64f56fc930b2056af9b33468ba}'
      # - --NotebookApp.password='${JUPYTER_PASSWORD-sha1:975a9425135d:7d3618cc7517de64f56fc930b2056af9b33468ba}'
    volumes:
      - ~/DataComposer/notebooks:/home/jovyan/work/notebooks/
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jupyter.rule=Host(`jupyter.localhost`)
      - traefik.http.routers.jupyter.service=jupyter
      - traefik.http.routers.jupyter.entrypoints=web,websecure
      - traefik.http.services.jupyter.loadbalancer.server.port=8888
      - traefik.http.routers.spark0.rule=Host(`spark.localhost`)
      - traefik.http.routers.spark0.service=spark0
      - traefik.http.routers.spark0.entrypoints=web,websecure
      - traefik.http.services.spark0.loadbalancer.server.port=4040
    environment:
      JUPYTER_ENABLE_LAB: ${JUPYTER_ENABLE_LAB-yes}
      NB_UID: $UID
      NB_GID: $GID
    networks:
      - traefik_net
networks:
    traefik_net:
      external: true
