version: '3'
services:
  metabase:
    image: metabase/metabase:latest
    volumes:
      - data:/metabase-data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.metabase.rule=Host(`metabase.localhost`)
      - traefik.http.routers.metabase.entrypoints=web,websecure
      - traefik.docker.network=traefik_net
    environment:
      JAVA_TIMEZONE: America/Sao_Paulo
      MB_DB_FILE: /metabase-data/metabase.db
      # MB_DB_TYPE: postgres
      # MB_DB_DBNAME: metabase
      # MB_DB_PORT: 5432
      # MB_DB_USER: metabase
      # MB_DB_PASS: ''
      # MB_DB_HOST: ''
      MUID: $UID
      MGID: $GID
    networks:
      - traefik_net
      - dbs_mysql
networks:
    traefik_net:
      external: true
    dbs_mysql:
      external: true
volumes:
  data: