version: '3'

services:
   minecraft:
      container_name: minecraft-easy
      image: lomot/minecraft-bedrock:latest
      ports:
         - 19132:19132/udp
      volumes:
         - /home/rdlu/Minecraft/data_2:/data
      restart: unless-stopped
      stdin_open: true
      tty: true
