version: '3'
services:
  n8n:
    image: n8nio/n8n
    environment:
      N8N_BASIC_AUTH_ACTIVE: ${N8N_AUTH-true}
      N8N_BASIC_AUTH_USER: ${N8N_USER-dlucomposer}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_PW-dlucomposer}
      # DB_TYPE: postgresdb
      # DB_POSTGRESDB_DATABASE: ${N8N_PG_DB-n8n}
      # DB_POSTGRESDB_HOST: ${N8N_PG_HOST-n8n_db}
      # DB_POSTGRESDB_PORT: ${N8N_PG_PORT-5432}
      # DB_POSTGRESDB_USER: ${N8N_PG_USER-n8n}
      # DB_POSTGRESDB_PASSWORD: ${N8N_PG_PW-n8n}
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.n8n.rule: Host(`n8n.localhost`) || Host(`n8n.${TRAEFIK_HOST-lan}`)
      traefik.http.routers.n8n.entrypoints: ${TRAEFIK_ENTRYPOINTS-web,websecure}
      traefik.http.routers.n8n.tls: ${SSL_ENABLE-false}
      traefik.http.services.n8n.loadbalancer.server.port: 5678
    networks:
      - default
      - traefik_net
  db:
    image: postgres
    container_name: n8n_db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${N8N_PG_PW-n8n}
      POSTGRES_USER: ${N8N_PG_USER-n8n}
      POSTGRES_DB: ${N8N_PG_DB-n8n}
networks:
  default:
  traefik_net:
    external: true
volumes:
  pgdata: