version: '3.3'

services:
  freshrss:
    image: linuxserver/freshrss
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=${TIMEZONE-UTC}
    volumes:
        - ${DOCKER_CONFIGS_PATH}/freshrss:/config
    restart: unless-stopped
    labels:
        traefik.enable: true
        traefik.http.routers.freshrss.rule: Host(`rss.localhost`) || Host(`rss.${TRAEFIK_HOST-lan}`) 
        traefik.http.routers.freshrss.entrypoints: ${TRAEFIK_ENTRYPOINTS-web,websecure}
        traefik.http.routers.freshrss.tls: ${SSL_ENABLE-false}
        traefik.http.services.freshrss.loadbalancer.server.port: 80
        traefik.docker.network: traefik_net
    networks:
        traefik_net:

networks:
  traefik_net:
    external: true
              